server:
    port : 8081
    error:
        include-message: always
        include-stacktrace: never
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
    application:
        name: credito
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dbteste?useSSL=false&useTimezone=true&serverTimezone=UTC
        username: root
        password: teste
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    sql:
        init:
            mode: always
            data-locations: classpath:data.sql